[tool.black]
line-length = 119
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
extend_skip_glob = ["venv"]
src_paths = ["isort", "test"]
skip = ["src/unitxt/dataset.py", "src/unitxt/metric.py"]

[tool.pydocstyle]
convention = "google"
add_select = ["D101"]
